# Generated by Django 5.2.6 on 2025-10-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ativo_id', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('close', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
            options={
                'unique_together': {('ativo_id', 'data')},
            },
        ),
    ]
