# Generated by Django 5.2.6 on 2025-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('close', models.FloatField()),
                ('status', models.CharField(max_length=10)),
                ('data', models.DateField()),
            ],
        ),
    ]
